# Generated by Django 6.0 on 2025-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Copyright",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sl_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Year"
                    ),
                ),
                (
                    "faculty_students",
                    models.TextField(
                        blank=True, null=True, verbose_name="Name of Faculty/Students"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title of Copy rights"
                    ),
                ),
                (
                    "filing_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Filing Informations"
                    ),
                ),
                (
                    "inventors",
                    models.TextField(blank=True, null=True, verbose_name="Inventor(s)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Copyright",
                "verbose_name_plural": "Copyrights",
                "db_table": "copyrights",
                "ordering": ["-year", "-sl_no"],
            },
        ),
        migrations.CreateModel(
            name="PatentFiled",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sl_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "date_of_filing",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Date of Filing",
                    ),
                ),
                (
                    "inventors",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Inventor(s)/Faculty/Student",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title of Patent"
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Application Number",
                    ),
                ),
                (
                    "date_of_publication",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Date of Publication",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, null=True, verbose_name="Abstract"),
                ),
                (
                    "applicant_name",
                    models.TextField(
                        blank=True, null=True, verbose_name="Applicant Name"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patent (Filed)",
                "verbose_name_plural": "Patents (Filed)",
                "db_table": "patents_filed",
                "ordering": ["-date_of_filing", "-sl_no"],
            },
        ),
        migrations.CreateModel(
            name="PatentGranted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sl_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Serial Number"
                    ),
                ),
                (
                    "granted_patent_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Granted Patent No.",
                    ),
                ),
                (
                    "date_of_grant",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Date of Grant",
                    ),
                ),
                (
                    "inventors",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Inventor(s)/Faculty/Student",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, null=True, verbose_name="Title of Patent"
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Application Number",
                    ),
                ),
                (
                    "date_of_publication",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Date of Publication",
                    ),
                ),
                (
                    "filing_institute",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Patent Filing Institute/Individual(s)",
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, null=True, verbose_name="Abstract"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Patent (Granted)",
                "verbose_name_plural": "Patents (Granted)",
                "db_table": "patents_granted",
                "ordering": ["-date_of_grant", "-sl_no"],
            },
        ),
    ]
