# Generated by Django 6.0 on 2025-12-25 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "field_definitions",
                    models.JSONField(
                        default=list,
                        help_text="JSON array defining fields for this category",
                        verbose_name="Field Definitions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Category",
                "verbose_name_plural": "IP Categories",
                "db_table": "ip_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntellectualProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object storing field values",
                        verbose_name="IP Data",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="patents.ipcategory",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intellectual Property",
                "verbose_name_plural": "Intellectual Properties",
                "db_table": "intellectual_properties",
                "ordering": ["-created_at"],
            },
        ),
    ]
