# Generated by Django 5.1.5 on 2026-04-11 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("patents", "0002_ipcategory_intellectualproperty"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="copyright",
            options={
                "ordering": ["-year"],
                "verbose_name": "Copyright",
                "verbose_name_plural": "Copyrights",
            },
        ),
        migrations.AlterModelOptions(
            name="patentfiled",
            options={
                "ordering": ["-date_of_filing"],
                "verbose_name": "Patent (Filed)",
                "verbose_name_plural": "Patents (Filed)",
            },
        ),
        migrations.AlterModelOptions(
            name="patentgranted",
            options={
                "ordering": ["-date_of_grant"],
                "verbose_name": "Patent (Granted)",
                "verbose_name_plural": "Patents (Granted)",
            },
        ),
        migrations.RemoveField(
            model_name="copyright",
            name="sl_no",
        ),
        migrations.RemoveField(
            model_name="patentfiled",
            name="sl_no",
        ),
        migrations.RemoveField(
            model_name="patentgranted",
            name="sl_no",
        ),
    ]
